python ./run_qa.py \
  --model_name_or_path microsoft/deberta-v3-base \
  --train_file ./data/GDPR120Q_train_formatted.json \
  --validation_file ./data/GDPR120Q_validation_formatted.json \
  --test_file ./data/GDPR120Q_test_formatted.json \
  --do_train \
  --do_predict \
  --per_device_train_batch_size 3 \
  --learning_rate 3e-5 \
  --num_train_epochs 5 \
  --max_seq_length 384 \
  --doc_stride 128 \
  --version_2_with_negative \
  --output_dir ./models/deberta-v3-base-10000 \
  --logging_dir ./logs/deberta-v3-base-10000 \
  --logging_steps 1000 \
  --evaluation_strategy epoch \
  --save_strategy epoch \
  --load_best_model_at_end \
  --save_total_limit 1 \
  --metric_for_best_model f1 \
  --max_train_samples 10000
